<?php
use CRM_Eck_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_ECK_Custom_Groups',
    'entity' => 'SavedSearch',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'ECK_Custom_Groups',
        'label' => E::ts('ECK Custom Groups'),
        'api_entity' => 'CustomGroup',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'title',
            'is_active',
            'extends',
            'extends_entity_column_value:label',
            'style:label',
            'is_reserved',
            'COUNT(CustomGroup_CustomField_custom_group_id_01.id) AS COUNT_CustomGroup_CustomField_custom_group_id_01_id',
            'GROUP_CONCAT(DISTINCT CustomGroup_CustomField_custom_group_id_01.label) AS GROUP_CONCAT_CustomGroup_CustomField_custom_group_id_01_label',
          ],
          'where' => [],
          'groupBy' => ['id'],
          'join' => [
            [
              'CustomField AS CustomGroup_CustomField_custom_group_id_01',
              'LEFT',
              [
                'id',
                '=',
                'CustomGroup_CustomField_custom_group_id_01.custom_group_id',
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_ECK_Custom_Groups_SearchDisplay_ECK_Custom_Groups',
    'entity' => 'SearchDisplay',
    'cleanup' => 'always',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'ECK_Custom_Groups',
        'label' => E::ts('ECK Custom Groups'),
        'saved_search_id.name' => 'ECK_Custom_Groups',
        'type' => 'table',
        'settings' => [
          'actions' => FALSE,
          'limit' => 20,
          'classes' => ['table', 'table-striped', 'table-bordered'],
          'pager' => [
            'show_count' => FALSE,
            'expose_limit' => FALSE,
            'hide_single' => TRUE,
          ],
          'sort' => [
            'weight' => 'ASC',
          ],
          'draggable' => 'weight',
          'cssRules' => [
            ['disabled', 'is_active', '=', FALSE],
          ],
          'placeholder' => 5,
          'toolbar' => [
            [
              'entity' => 'CustomGroup',
              'target' => 'crm-popup',
              'style' => 'primary',
              'text' => E::ts('Add Set of Custom Fields'),
              'icon' => 'fa-plus',
              'path' => 'civicrm/admin/custom/group/edit?action=add&reset=1&extends=[extends]',
              'task' => '',
              'join' => '',
              'condition' => [],
            ],
          ],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'title',
              'label' => E::ts('Custom Group'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'extends_entity_column_value:label',
              'label' => E::ts('Subtypes'),
              'empty_value' => E::ts('All'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'is_active',
              'label' => E::ts('Enabled'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'style:label',
              'label' => E::ts('Style'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'html',
              'key' => 'GROUP_CONCAT_CustomGroup_CustomField_custom_group_id_01_label',
              'label' => E::ts('Fields'),
              'sortable' => TRUE,
              'rewrite' => "{capture assign=fields}[GROUP_CONCAT_CustomGroup_CustomField_custom_group_id_01_label]{/capture}{\$fields|replace:',':'<br>'}",
            ],
            [
              'size' => 'btn-xs',
              'links' => [
                [
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '',
                  'icon' => 'fa-list-alt',
                  'text' => E::ts('Fields (%1)', [1 => '[COUNT_CustomGroup_CustomField_custom_group_id_01_id]']),
                  'style' => 'default',
                  'path' => 'civicrm/admin/custom/group/fields#/?gid=[id]',
                  'condition' => [],
                  'task' => '',
                  'conditions' => [],
                ],
                [
                  'entity' => 'CustomGroup',
                  'action' => 'update',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Settings'),
                  'style' => 'default',
                  'path' => '',
                  'condition' => [],
                  'task' => '',
                  'conditions' => [],
                ],
              ],
              'type' => 'buttons',
              'alignment' => 'text-right',
            ],
            [
              'text' => '',
              'style' => 'default',
              'size' => 'btn-xs',
              'icon' => 'fa-bars',
              'links' => [
                [
                  'entity' => 'CustomGroup',
                  'action' => 'preview',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-eye',
                  'text' => E::ts('Preview'),
                  'style' => 'default',
                  'path' => '',
                  'condition' => [],
                  'task' => '',
                  'conditions' => [],
                ],
                [
                  'task' => 'enable',
                  'entity' => 'CustomGroup',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-on',
                  'text' => E::ts('Enable'),
                  'style' => 'default',
                  'condition' => [],
                  'path' => '',
                  'action' => '',
                  'join' => '',
                  'conditions' => [],
                ],
                [
                  'task' => 'disable',
                  'entity' => 'CustomGroup',
                  'target' => 'crm-popup',
                  'icon' => 'fa-toggle-off',
                  'text' => E::ts('Disable'),
                  'style' => 'default',
                  'condition' => [],
                  'path' => '',
                  'action' => '',
                  'join' => '',
                  'conditions' => [],
                ],
                [
                  'entity' => 'CustomGroup',
                  'action' => 'delete',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete'),
                  'style' => 'danger',
                  'path' => '',
                  'condition' => [],
                  'task' => '',
                  'conditions' => [],
                ],
                [
                  'entity' => 'CustomField',
                  'action' => 'add',
                  'join' => 'CustomGroup_CustomField_custom_group_id_01',
                  'target' => 'crm-popup',
                  'style' => 'default',
                  'text' => E::ts('Add Custom Field'),
                  'icon' => 'fa-plus',
                  'path' => '',
                  'task' => '',
                  'condition' => [],
                  'conditions' => [],
                ],
              ],
              'type' => 'menu',
              'alignment' => 'text-right',
            ],
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
